name: mytorch
channels:
    - nvidia
dependencies:
    # Hugging Face
    - accelerate
    - datasets
    - evaluate
    - transformers

    # Util
    - pytorch::pytorch
    - pytorch::pytorch-cuda

    # Why not?
    - conda-forge::jaxlib
    - conda-forge::jax

    # Notebooks
    - jupyterlab
    - ipywidgets

    # Data analysis
    - matplotlib

    - pandas
    - polars
    - scikit-learn

    # Development
    - mypy
    - black

