name: mytorch
channels:
    - nvidia
dependencies:
    # Hugging Face
    - conda-forge::accelerate
    - conda-forge::datasets
    - conda-forge::evaluate
    - conda-forge::transformers
    - huggingface::safetensors

    # Util
    - pytorch::pytorch
    - pytorch::pytorch-cuda
    - conda-forge::lightning

    # Why not?
    - conda-forge::jaxlib
    - conda-forge::jax

    # Notebooks
    - jupyterlab
    - ipywidgets

    # Data analysis
    - matplotlib

    - pandas
    - polars
    - scikit-learn

    # Development
    - mypy
    - black
    - python-language-server
    - pyls-black

    # Only available with pip
    - pip
    - pip:
        - bertviz
        - ecco

